# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.ModelCheckpoint.html

model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${paths.output_dir}/checkpoints  # directory to save the model file
  filename: checkpoint_{step:03d}  # checkpoint filename with step information
  monitor: null  # Since you want to save every N steps, set monitor to null
  verbose: False  # verbosity mode
  save_last: False  # additionally always save an exact copy of the last checkpoint to a file last.ckpt
  save_top_k: 0  # Since you want to save every N steps, set save_top_k to 0
  mode: "max"  # "max" means higher metric value is better, can be also "min"
  auto_insert_metric_name: False  # We are not using a specific metric, so set this to False
  save_weights_only: False  # if True, then only the model’s weights will be saved
  every_n_train_steps: 10  # number of training steps between checkpoints
  train_time_interval: null  # checkpoints are monitored at the specified time interval
  every_n_epochs: 1  # number of epochs between checkpoints
  save_on_train_epoch_end: False  # Whether to run checkpointing at the end of the training epoch or the end of validation

